--DROPS SECTION--
DROP TABLE IF EXISTS esdbempresarial.TBL_SITUACION;
DROP TABLE IF EXISTS esdbempresarial.TBL_EVALUACION;
DROP TABLE IF EXISTS esdbempresarial.TBL_BANDEJA;
DROP TABLE IF EXISTS esdbempresarial.TBL_DOCUMENTOS;
DROP TABLE IF EXISTS esdbempresarial.TBL_FILE;
DROP TABLE IF EXISTS esdbempresarial.TBL_SOCIOS;
DROP TABLE IF EXISTS esdbempresarial.TBL_EMPRESA;
DROP TABLE IF EXISTS esdbempresarial.TBL_COLABORADORES; 
DROP TABLE IF EXISTS esdbempresarial.TBL_BANCO;
--END OF DROPS SECTION--

--TABLE EMPRESA--
CREATE TABLE esdbempresarial.TBL_EMPRESA (
	codigo 			INTEGER NOT NULL,
	razonsocial 	VARCHAR(200) NULL
) TABLESPACE ts_data;

ALTER TABLE IF EXISTS esdbempresarial.TBL_EMPRESA
 ADD CONSTRAINT XPKTBL_EMPRESA PRIMARY KEY (codigo);
--END OF TABLE EMPRESA--
CREATE TABLE esdbempresarial.TBL_SOCIOS (
	codigo 			INTEGER NOT NULL,
	nombre 			VARCHAR(200) NOT NULL,
	representante 	CHAR(1) NULL,
	empresa 		INTEGER NOT NULL
) TABLESPACE ts_data;

ALTER TABLE IF EXISTS esdbempresarial.TBL_SOCIOS 
ADD CONSTRAINT XPKTBL_SOCIOS PRIMARY KEY (codigo);

ALTER TABLE IF EXISTS esdbempresarial.TBL_SOCIOS
ADD CONSTRAINT R1FK_SOCIOS_EMPRESA FOREIGN KEY (empresa) 
REFERENCES esdbempresarial.TBL_EMPRESA (codigo);

CREATE TABLE esdbempresarial.TBL_BANCO (
	codigo 			INTEGER NOT NULL,
	razonsocial 	VARCHAR(200) NULL
) TABLESPACE ts_data;

ALTER TABLE IF EXISTS esdbempresarial.TBL_BANCO
 ADD CONSTRAINT XPKTBL_BANCO PRIMARY KEY (codigo);


CREATE TABLE esdbempresarial.TBL_COLABORADORES (
	codigo 			INTEGER NOT NULL,
	nombre 			VARCHAR(200) NOT NULL,
	representante 	CHAR(1) NULL,
	banco 			INTEGER NOT NULL
) TABLESPACE ts_data;

ALTER TABLE IF EXISTS esdbempresarial.TBL_COLABORADORES 
ADD CONSTRAINT XPKTBL_COLABORADORES PRIMARY KEY (codigo);

ALTER TABLE IF EXISTS esdbempresarial.TBL_COLABORADORES
ADD CONSTRAINT R2FK_COLABORADORES_BANCO FOREIGN KEY (banco) 
REFERENCES esdbempresarial.TBL_BANCO (codigo);

CREATE TABLE esdbempresarial.TBL_FILE(
	codigo			INTEGER NOT NULL,
	socio 			INTEGER NOT NULL,
	causal			VARCHAR(200) NULL
) TABLESPACE ts_data;

ALTER TABLE IF EXISTS esdbempresarial.TBL_FILE
ADD CONSTRAINT XPKTBL_FILE PRIMARY KEY (codigo,socio);

ALTER TABLE IF EXISTS esdbempresarial.TBL_FILE
add CONSTRAINT R3FK_FILE_SOCIOS FOREIGN KEY (socio)
REFERENCES esdbempresarial.TBL_SOCIOS(codigo);

CREATE TABLE esdbempresarial.TBL_DOCUMENTOS(
	codigo			INTEGER NOT NULL,
	file            INTEGER NOT NULL,
	socio 			INTEGER NOT NULL,
	causal			VARCHAR(200) NULL
) TABLESPACE ts_data;

ALTER TABLE IF EXISTS esdbempresarial.TBL_DOCUMENTOS
ADD CONSTRAINT XPKTBL_DOCUMENTOS PRIMARY KEY (codigo,socio,file);

ALTER TABLE IF EXISTS esdbempresarial.TBL_DOCUMENTOS
add CONSTRAINT R4FK_DOCUMENTOS_FILE FOREIGN KEY (file,socio)
REFERENCES esdbempresarial.TBL_FILE(codigo,socio);

CREATE TABLE esdbempresarial.TBL_BANDEJA(
	codigo			INTEGER NOT NULL,
	enviapor 		INTEGER NULL,
	fechaingreso	TIMESTAMP NOT NULL,
	fechaatencion	TIMESTAMP NULL,
	causal			VARCHAR(200) NULL,
	colaborador 	INTEGER NOT NULL
) TABLESPACE ts_data;

ALTER TABLE IF EXISTS esdbempresarial.TBL_BANDEJA
ADD CONSTRAINT XPKTBL_BANDEJA PRIMARY KEY (codigo);

ALTER TABLE IF EXISTS esdbempresarial.TBL_BANDEJA
ADD CONSTRAINT R5FK_BANDEJA_COLABORADOR FOREIGN KEY (colaborador)
REFERENCES esdbempresarial.TBL_COLABORADORES(codigo);

CREATE TABLE esdbempresarial.TBL_EVALUACION(	
	bandeja 		INTEGER NOT NULL,		
	file 			INTEGER NOT NULL,
	socio 			INTEGER NOT NULL,
	causal			VARCHAR(200) NULL,
	fechainicio		TIMESTAMP NOT NULL,
	fechafin		TIMESTAMP NULL
) TABLESPACE ts_data;

ALTER TABLE IF EXISTS esdbempresarial.TBL_EVALUACION
ADD CONSTRAINT XPKTBL_EVALUACION PRIMARY KEY (bandeja,socio,file);

ALTER TABLE IF EXISTS esdbempresarial.TBL_EVALUACION
add CONSTRAINT R6FK_EVALUACION_FILE FOREIGN KEY (file,socio)
REFERENCES esdbempresarial.TBL_FILE(codigo,socio);

ALTER TABLE IF EXISTS esdbempresarial.TBL_EVALUACION
add CONSTRAINT R7FK_EVALUACION_BANDEJA FOREIGN KEY (bandeja)
REFERENCES esdbempresarial.TBL_BANDEJA(codigo);

CREATE TABLE esdbempresarial.TBL_SITUACION(
	codigo			INTEGER NOT NULL,
	bandeja 		INTEGER NOT NULL,
	file            INTEGER NOT NULL,
	socio 			INTEGER NOT NULL,
	causal			VARCHAR(200) NULL
) TABLESPACE ts_data;

ALTER TABLE IF EXISTS esdbempresarial.TBL_SITUACION
ADD CONSTRAINT XPKTBL_SITUACION PRIMARY KEY (codigo);

ALTER TABLE IF EXISTS esdbempresarial.TBL_SITUACION
add CONSTRAINT R8FK_SITUACION_EVALUACION FOREIGN KEY (bandeja,file,socio)
REFERENCES esdbempresarial.TBL_EVALUACION(bandeja,file,socio);